server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/test;MODE=MariaDB
    url: jdbc:h2:mem:test;MODE=MariaDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  data:
    storage-type: redis
    redis:
      host: localhost
      port: 6379
      #password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: arheon2469@gmail.com
    password: mcmqukivwvjsbhhx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: 7ZmA656AIOuTneygkOyZlSDquLDsm5AgMeydvOywqALdlsKJL3234jklsdjfaKJDLnflkasdf

kakao:
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
  grant-type: authorization_code
  client-id: 049ebf43b54fe431e060d0aa0a8e39af
  redirect-uri: http://localhost:8080/api/auth/kakao/login

logging:
  level:
    '[com.mid]': DEBUG
    '[org.hibernate.type]': TRACE
